name: Deploy code to test
on:
  push:
    branches:
      - main
steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy changed files to remote server
      env:
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USERNAME: ${{ secrets.USERNAME }}
        REMOTE_PASSWORD: ${{ secrets.PASSWORD }}
        REMOTE_DESTINATION: /home/thecubver/repositories/andrea
      run: |
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
        scp -o StrictHostKeyChecking=no -r ${CHANGED_FILES} ${USERNAME}@${HOST}:${REMOTE_DESTINATION}