name: Deploy code to test
on:
  push:
    branches:
      - B2C-user-login
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to test
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: touch /home/thecubver/text